language: ruby
rvm:
- 2.2.0
deploy:
  99a530a1-908f-4911-9afe-540b894f2538:
    secure: noGHlCIaE4YABZmvV1YEYgSrAz9xOg3ZJDTErbyICx0CYKyu8nYRotgWt5XAVHX0qBT3oW4sIklBfWFRQe3zmq5vyq6WmnVUx4sy/sf24ie5oLHvssxcok7p627WICSnec5kofTf5cwYVW9BqDbKo+CTUaaHULGRFvQhUay1E0AQqodoYWNgSSCbPx+waKjODK9WDVkUd5Oypt9TM2yFmD0Att/JM2wTNCgvjpMUjUXP+MIhMgUJqumjkCuQZonOJOMuVNI/Cz/zijQNNhnLSKRd/BUUb740N46i6wBv1xuVQYCWV5W8DmMtVO9ududbTt+/QioDdz8IZYrYyqDDyU3h5VgS2CQ7QUIqoZSGFgmem4OKmIc/wT9BtAM+U4ee4n+hhPmlgg6QsqYZYa7YBsfJdU7+q5j2h70Udm5uX0vU262ZKVqR+SDYWbjNG2d57CVMQrtZvVanoM+Ud3xbpNS6mu4yfKJdEqIKjNhtGbJLnfWteycHWgnee4bW7CQoZOQqv6E6q4zBCTHBErtD0rnXzUKyM51AoXBXBNfgr+Bo+Tp2sbiqtqRQf6BWpYW6NR/u5RhUsOtW2mX0ReKhCDzG6L0MwFnMqiGcX0nNTCzmGEqK/FERi/XxhopPIzcJtvvMS2R7CAgEBOX7EqLExUb00rKeV1B84Zuwdu3Dw7U=
